---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-{{ include "vehicle-command.name" . }}-https
spec:
  entryPoints:
    - websecure
  tls:
    passthrough: true
  routes:
    - kind: HostSNI(`commands.myteslamate.com`)
      services:
        - name: {{ include "vehicle-command.fullname" . }}
          port: {{ .Values.service.port }}