---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-{{ include "vehicle-command.name" . }}-https
spec:
  entryPoints:
    - websecure
  tls:
    secretName: app-tls
  routes:
    - kind: Rule
      match: Host(`vehicle-command.myteslamate.com`)
      services:
        - name: {{ include "vehicle-command.fullname" . }}
          port: {{ .Values.service.port }}